name: Testes Unitários

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar o Java e Node.js
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'  # Altere para '8' para usar o Java 8

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Conceder permissões de execução ao Maven Wrapper
      run: chmod +x mvnw

    - name: Executar os testes
      run: ./mvnw -f forum-api-main/pom.xml test
